- name: Ensure system is up-to-date
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Apache
  apt:
    name: apache2
    state: latest

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes
