- name: Ensure system is up-to-date
  apt:
    upgrade: dist
    update_cache: yes

- name: Install MySQL
  apt:
    name: mysql-server
    state: latest

- name: Install Python MySQL dependency for Ansible
  apt:
    name: python3-pymysql
    state: present
  become: true

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Secure MySQL Installation (set root password)
  mysql_user:
    login_user: root
    login_password: ""
    name: root
    password: "{{ vault_mysql_root_password }}"
    host_all: yes
    state: present
