- name: Ensure system is up-to-date
  apt:
    upgrade: dist
    update_cache: yes

- name: Install MySQL
  apt:
    name: mysql-server
    state: latest

- name: Install Python MySQL dependency for Ansible
  apt:
    name: python3-pymysql
    state: present
  become: true

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Secure MySQL Installation (set root password)
  mysql_user:
    name: root
    password: "{{ vault_mysql_root_password }}"
    host_all: yes
    login_user: root
    login_password: "{{ vault_mysql_root_password }}"
    state: present
    update_password: always
  become: true

- name: Create MySQL root credentials file
  template:
    src: root-my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Confirm root can log in with new password
  mysql_user:
    name: root
    login_user: root
    login_password: "{{ vault_mysql_root_password }}"
    state: present
  become: true
