name: Production Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Create SSH Key File
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/aws-prod.pem
        chmod 600 ~/.ssh/aws-prod.pem

    - name: Run playbook
      run: |
        ansible-playbook -i inventories/production/hosts roles/apache/tasks/main.yml \
          --vault-password-file vault_pass.txt
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
